name: Slack Notification Only

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: self-hosted

    steps:
      - name: Simulate job
        run: echo "Deploying app..."

      - name: Slack Notify Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ SUCCESS: $GITHUB_REPOSITORY deployed on $GITHUB_REF_NAME\"}" \
          ${{ secrets.SLACK_WEBHOOK }}
      - name: Slack Notify Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ FAILED: $GITHUB_REPOSITORY on $GITHUB_REF_NAME\"}" \
          ${{ secrets.SLACK_WEBHOOK }}
